pipeline {
    agent any
    options {
        checkoutToSubdirectory('job/docker_images/')
    }

    stages {
        stage('Update all docker images...') {
            steps {
                sh './jobs/docker_images/upgrade_all_images.sh'
            }
        } // End stage
        stage('Prune all unused docker images...') {
            steps {
                sh '''#!/bin/bash
                    docker image prune --force
                '''
            }
        } // End stage
    } // End stages
    post {
        always {
            echo 'List all docker images...'
            sh 'docker images'
        }
    }
}
