
pipeline {
    agent any
    options {
        skipDefaultCheckout() // Manual checkout stage
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM', branches: [[name: '**']],
                    extensions: [
                        [$class: 'SparseCheckoutPaths',
                         sparseCheckoutPaths: [[path: 'jobs/remote_update']]],
                        [$class: 'CloneOption', depth: 1, noTags: false,
                         reference: '', shallow: true]
                    ],
                    userRemoteConfigs: [
                        [url: 'https://github.com/ChunPanYung/jenkins_as_code']
                    ]
                ])
            }
        } // End stage('Checkout')

        stage('Remote SSH') {
            environment {
                SSH_KEY = credentials('ssh-server')
            }
            steps {
                script{ 
                    def remote = [:]
                    remote.name = 'server'
                    remote.host = 'cloud.lan'
                    remote.allowAnyHosts = true

                    remote.user = SSH_KEY_USR
                    remote.identityFile = SSH_KEY

                    sshCommand remote: remote, command: 'ls'
                }
            }
        } // End stage Remote SSH
    } // End stages
}
